import type { RawPrice, MarketFactor } from "./types";

// 6 weeks of realistic seed data for Boston and Seattle
// Week dates: Mon of each week going back 6 weeks from Feb 10, 2026

export const WEEKS = [
  "2025-12-29",
  "2026-01-05",
  "2026-01-12",
  "2026-01-19",
  "2026-01-26",
  "2026-02-02",
  "2026-02-10",
];

export const BOSTON_PRICES: Record<string, RawPrice[]> = {
  "2025-12-29": [
    { restaurant: "McDonald's", burger: "Big Mac", price: 6.49, source: "menu", category: "fast_food" },
    { restaurant: "Five Guys", burger: "Cheeseburger", price: 11.69, source: "menu", category: "fast_food" },
    { restaurant: "Shake Shack", burger: "ShackBurger", price: 8.49, source: "website", category: "fast_food" },
    { restaurant: "Wendy's", burger: "Dave's Single", price: 6.29, source: "menu", category: "fast_food" },
    { restaurant: "Mr. Bartley's", burger: "Bartley's Classic", price: 14.50, source: "menu", category: "casual" },
    { restaurant: "Tasty Burger", burger: "Tasty Burger", price: 8.95, source: "website", category: "casual" },
    { restaurant: "Boston Burger Co.", burger: "The Bostonian", price: 15.99, source: "doordash", category: "casual" },
    { restaurant: "JM Curley", burger: "Curley Burger", price: 16.00, source: "menu", category: "casual" },
    { restaurant: "Waypoint", burger: "Wagyu Smash Burger", price: 22.00, source: "menu", category: "premium" },
    { restaurant: "The Stockyard", burger: "Dry-Aged Burger", price: 24.00, source: "website", category: "premium" },
    { restaurant: "Grill 23", burger: "Prime Burger", price: 26.00, source: "menu", category: "premium" },
  ],
  "2026-01-05": [
    { restaurant: "McDonald's", burger: "Big Mac", price: 6.49, source: "menu", category: "fast_food" },
    { restaurant: "Five Guys", burger: "Cheeseburger", price: 11.69, source: "menu", category: "fast_food" },
    { restaurant: "Shake Shack", burger: "ShackBurger", price: 8.49, source: "website", category: "fast_food" },
    { restaurant: "Wendy's", burger: "Dave's Single", price: 6.29, source: "menu", category: "fast_food" },
    { restaurant: "Mr. Bartley's", burger: "Bartley's Classic", price: 14.95, source: "menu", category: "casual" },
    { restaurant: "Tasty Burger", burger: "Tasty Burger", price: 8.95, source: "website", category: "casual" },
    { restaurant: "Boston Burger Co.", burger: "The Bostonian", price: 15.99, source: "doordash", category: "casual" },
    { restaurant: "JM Curley", burger: "Curley Burger", price: 16.00, source: "menu", category: "casual" },
    { restaurant: "Waypoint", burger: "Wagyu Smash Burger", price: 22.00, source: "menu", category: "premium" },
    { restaurant: "The Stockyard", burger: "Dry-Aged Burger", price: 24.00, source: "website", category: "premium" },
    { restaurant: "Grill 23", burger: "Prime Burger", price: 27.00, source: "menu", category: "premium" },
  ],
  "2026-01-12": [
    { restaurant: "McDonald's", burger: "Big Mac", price: 6.49, source: "menu", category: "fast_food" },
    { restaurant: "Five Guys", burger: "Cheeseburger", price: 11.99, source: "menu", category: "fast_food" },
    { restaurant: "Shake Shack", burger: "ShackBurger", price: 8.79, source: "website", category: "fast_food" },
    { restaurant: "Wendy's", burger: "Dave's Single", price: 6.29, source: "menu", category: "fast_food" },
    { restaurant: "Mr. Bartley's", burger: "Bartley's Classic", price: 14.95, source: "menu", category: "casual" },
    { restaurant: "Tasty Burger", burger: "Tasty Burger", price: 9.25, source: "website", category: "casual" },
    { restaurant: "Boston Burger Co.", burger: "The Bostonian", price: 16.49, source: "doordash", category: "casual" },
    { restaurant: "JM Curley", burger: "Curley Burger", price: 16.00, source: "menu", category: "casual" },
    { restaurant: "Waypoint", burger: "Wagyu Smash Burger", price: 22.00, source: "menu", category: "premium" },
    { restaurant: "The Stockyard", burger: "Dry-Aged Burger", price: 24.00, source: "website", category: "premium" },
    { restaurant: "Grill 23", burger: "Prime Burger", price: 27.00, source: "menu", category: "premium" },
  ],
  "2026-01-19": [
    { restaurant: "McDonald's", burger: "Big Mac", price: 6.69, source: "menu", category: "fast_food" },
    { restaurant: "Five Guys", burger: "Cheeseburger", price: 11.99, source: "menu", category: "fast_food" },
    { restaurant: "Shake Shack", burger: "ShackBurger", price: 8.79, source: "website", category: "fast_food" },
    { restaurant: "Wendy's", burger: "Dave's Single", price: 6.49, source: "menu", category: "fast_food" },
    { restaurant: "Mr. Bartley's", burger: "Bartley's Classic", price: 15.50, source: "menu", category: "casual" },
    { restaurant: "Tasty Burger", burger: "Tasty Burger", price: 9.25, source: "website", category: "casual" },
    { restaurant: "Boston Burger Co.", burger: "The Bostonian", price: 16.49, source: "doordash", category: "casual" },
    { restaurant: "JM Curley", burger: "Curley Burger", price: 17.00, source: "menu", category: "casual" },
    { restaurant: "Waypoint", burger: "Wagyu Smash Burger", price: 23.00, source: "menu", category: "premium" },
    { restaurant: "The Stockyard", burger: "Dry-Aged Burger", price: 24.00, source: "website", category: "premium" },
    { restaurant: "Grill 23", burger: "Prime Burger", price: 27.00, source: "menu", category: "premium" },
  ],
  "2026-01-26": [
    { restaurant: "McDonald's", burger: "Big Mac", price: 6.69, source: "menu", category: "fast_food" },
    { restaurant: "Five Guys", burger: "Cheeseburger", price: 11.99, source: "menu", category: "fast_food" },
    { restaurant: "Shake Shack", burger: "ShackBurger", price: 8.79, source: "website", category: "fast_food" },
    { restaurant: "Wendy's", burger: "Dave's Single", price: 6.49, source: "menu", category: "fast_food" },
    { restaurant: "Mr. Bartley's", burger: "Bartley's Classic", price: 15.50, source: "menu", category: "casual" },
    { restaurant: "Tasty Burger", burger: "Tasty Burger", price: 9.50, source: "website", category: "casual" },
    { restaurant: "Boston Burger Co.", burger: "The Bostonian", price: 16.99, source: "doordash", category: "casual" },
    { restaurant: "JM Curley", burger: "Curley Burger", price: 17.00, source: "menu", category: "casual" },
    { restaurant: "Waypoint", burger: "Wagyu Smash Burger", price: 23.00, source: "menu", category: "premium" },
    { restaurant: "The Stockyard", burger: "Dry-Aged Burger", price: 25.00, source: "website", category: "premium" },
    { restaurant: "Grill 23", burger: "Prime Burger", price: 27.00, source: "menu", category: "premium" },
  ],
  "2026-02-02": [
    { restaurant: "McDonald's", burger: "Big Mac", price: 6.69, source: "menu", category: "fast_food" },
    { restaurant: "Five Guys", burger: "Cheeseburger", price: 12.29, source: "menu", category: "fast_food" },
    { restaurant: "Shake Shack", burger: "ShackBurger", price: 8.99, source: "website", category: "fast_food" },
    { restaurant: "Wendy's", burger: "Dave's Single", price: 6.49, source: "menu", category: "fast_food" },
    { restaurant: "Mr. Bartley's", burger: "Bartley's Classic", price: 15.50, source: "menu", category: "casual" },
    { restaurant: "Tasty Burger", burger: "Tasty Burger", price: 9.50, source: "website", category: "casual" },
    { restaurant: "Boston Burger Co.", burger: "The Bostonian", price: 16.99, source: "doordash", category: "casual" },
    { restaurant: "JM Curley", burger: "Curley Burger", price: 17.00, source: "menu", category: "casual" },
    { restaurant: "Waypoint", burger: "Wagyu Smash Burger", price: 24.00, source: "menu", category: "premium" },
    { restaurant: "The Stockyard", burger: "Dry-Aged Burger", price: 25.00, source: "website", category: "premium" },
    { restaurant: "Grill 23", burger: "Prime Burger", price: 28.00, source: "menu", category: "premium" },
  ],
  "2026-02-10": [
    { restaurant: "McDonald's", burger: "Big Mac", price: 6.69, source: "menu", category: "fast_food" },
    { restaurant: "Five Guys", burger: "Cheeseburger", price: 12.29, source: "menu", category: "fast_food" },
    { restaurant: "Shake Shack", burger: "ShackBurger", price: 8.99, source: "website", category: "fast_food" },
    { restaurant: "Wendy's", burger: "Dave's Single", price: 6.49, source: "menu", category: "fast_food" },
    { restaurant: "Mr. Bartley's", burger: "Bartley's Classic", price: 15.95, source: "menu", category: "casual" },
    { restaurant: "Tasty Burger", burger: "Tasty Burger", price: 9.75, source: "website", category: "casual" },
    { restaurant: "Boston Burger Co.", burger: "The Bostonian", price: 16.99, source: "doordash", category: "casual" },
    { restaurant: "JM Curley", burger: "Curley Burger", price: 17.00, source: "menu", category: "casual" },
    { restaurant: "Waypoint", burger: "Wagyu Smash Burger", price: 24.00, source: "menu", category: "premium" },
    { restaurant: "The Stockyard", burger: "Dry-Aged Burger", price: 25.00, source: "website", category: "premium" },
    { restaurant: "Grill 23", burger: "Prime Burger", price: 28.00, source: "menu", category: "premium" },
  ],
};

export const SEATTLE_PRICES: Record<string, RawPrice[]> = {
  "2025-12-29": [
    { restaurant: "McDonald's", burger: "Big Mac", price: 6.29, source: "menu", category: "fast_food" },
    { restaurant: "Five Guys", burger: "Cheeseburger", price: 11.49, source: "menu", category: "fast_food" },
    { restaurant: "Shake Shack", burger: "ShackBurger", price: 8.29, source: "website", category: "fast_food" },
    { restaurant: "Dick's Drive-In", burger: "Dick's Deluxe", price: 4.25, source: "menu", category: "fast_food" },
    { restaurant: "Uneeda Burger", burger: "Classic Burger", price: 14.00, source: "menu", category: "casual" },
    { restaurant: "Red Mill Burgers", burger: "Red Mill Bacon Burger", price: 10.75, source: "website", category: "casual" },
    { restaurant: "Lil Woody's", burger: "Lil Woody's Burger", price: 11.50, source: "doordash", category: "casual" },
    { restaurant: "Katsu Burger", burger: "Original Katsu Burger", price: 13.50, source: "menu", category: "casual" },
    { restaurant: "Bateau", burger: "Dry-Aged Burger", price: 24.00, source: "menu", category: "premium" },
    { restaurant: "Eden Hill", burger: "Wagyu Burger", price: 22.00, source: "website", category: "premium" },
    { restaurant: "The Walrus", burger: "Smoked Brisket Burger", price: 19.00, source: "menu", category: "premium" },
  ],
  "2026-01-05": [
    { restaurant: "McDonald's", burger: "Big Mac", price: 6.29, source: "menu", category: "fast_food" },
    { restaurant: "Five Guys", burger: "Cheeseburger", price: 11.49, source: "menu", category: "fast_food" },
    { restaurant: "Shake Shack", burger: "ShackBurger", price: 8.29, source: "website", category: "fast_food" },
    { restaurant: "Dick's Drive-In", burger: "Dick's Deluxe", price: 4.25, source: "menu", category: "fast_food" },
    { restaurant: "Uneeda Burger", burger: "Classic Burger", price: 14.00, source: "menu", category: "casual" },
    { restaurant: "Red Mill Burgers", burger: "Red Mill Bacon Burger", price: 10.75, source: "website", category: "casual" },
    { restaurant: "Lil Woody's", burger: "Lil Woody's Burger", price: 11.50, source: "doordash", category: "casual" },
    { restaurant: "Katsu Burger", burger: "Original Katsu Burger", price: 13.50, source: "menu", category: "casual" },
    { restaurant: "Bateau", burger: "Dry-Aged Burger", price: 24.00, source: "menu", category: "premium" },
    { restaurant: "Eden Hill", burger: "Wagyu Burger", price: 22.00, source: "website", category: "premium" },
    { restaurant: "The Walrus", burger: "Smoked Brisket Burger", price: 19.50, source: "menu", category: "premium" },
  ],
  "2026-01-12": [
    { restaurant: "McDonald's", burger: "Big Mac", price: 6.29, source: "menu", category: "fast_food" },
    { restaurant: "Five Guys", burger: "Cheeseburger", price: 11.49, source: "menu", category: "fast_food" },
    { restaurant: "Shake Shack", burger: "ShackBurger", price: 8.49, source: "website", category: "fast_food" },
    { restaurant: "Dick's Drive-In", burger: "Dick's Deluxe", price: 4.25, source: "menu", category: "fast_food" },
    { restaurant: "Uneeda Burger", burger: "Classic Burger", price: 14.50, source: "menu", category: "casual" },
    { restaurant: "Red Mill Burgers", burger: "Red Mill Bacon Burger", price: 10.75, source: "website", category: "casual" },
    { restaurant: "Lil Woody's", burger: "Lil Woody's Burger", price: 12.00, source: "doordash", category: "casual" },
    { restaurant: "Katsu Burger", burger: "Original Katsu Burger", price: 13.50, source: "menu", category: "casual" },
    { restaurant: "Bateau", burger: "Dry-Aged Burger", price: 24.00, source: "menu", category: "premium" },
    { restaurant: "Eden Hill", burger: "Wagyu Burger", price: 22.00, source: "website", category: "premium" },
    { restaurant: "The Walrus", burger: "Smoked Brisket Burger", price: 19.50, source: "menu", category: "premium" },
  ],
  "2026-01-19": [
    { restaurant: "McDonald's", burger: "Big Mac", price: 6.49, source: "menu", category: "fast_food" },
    { restaurant: "Five Guys", burger: "Cheeseburger", price: 11.69, source: "menu", category: "fast_food" },
    { restaurant: "Shake Shack", burger: "ShackBurger", price: 8.49, source: "website", category: "fast_food" },
    { restaurant: "Dick's Drive-In", burger: "Dick's Deluxe", price: 4.25, source: "menu", category: "fast_food" },
    { restaurant: "Uneeda Burger", burger: "Classic Burger", price: 14.50, source: "menu", category: "casual" },
    { restaurant: "Red Mill Burgers", burger: "Red Mill Bacon Burger", price: 11.25, source: "website", category: "casual" },
    { restaurant: "Lil Woody's", burger: "Lil Woody's Burger", price: 12.00, source: "doordash", category: "casual" },
    { restaurant: "Katsu Burger", burger: "Original Katsu Burger", price: 14.00, source: "menu", category: "casual" },
    { restaurant: "Bateau", burger: "Dry-Aged Burger", price: 25.00, source: "menu", category: "premium" },
    { restaurant: "Eden Hill", burger: "Wagyu Burger", price: 22.00, source: "website", category: "premium" },
    { restaurant: "The Walrus", burger: "Smoked Brisket Burger", price: 19.50, source: "menu", category: "premium" },
  ],
  "2026-01-26": [
    { restaurant: "McDonald's", burger: "Big Mac", price: 6.49, source: "menu", category: "fast_food" },
    { restaurant: "Five Guys", burger: "Cheeseburger", price: 11.69, source: "menu", category: "fast_food" },
    { restaurant: "Shake Shack", burger: "ShackBurger", price: 8.49, source: "website", category: "fast_food" },
    { restaurant: "Dick's Drive-In", burger: "Dick's Deluxe", price: 4.50, source: "menu", category: "fast_food" },
    { restaurant: "Uneeda Burger", burger: "Classic Burger", price: 14.50, source: "menu", category: "casual" },
    { restaurant: "Red Mill Burgers", burger: "Red Mill Bacon Burger", price: 11.25, source: "website", category: "casual" },
    { restaurant: "Lil Woody's", burger: "Lil Woody's Burger", price: 12.00, source: "doordash", category: "casual" },
    { restaurant: "Katsu Burger", burger: "Original Katsu Burger", price: 14.00, source: "menu", category: "casual" },
    { restaurant: "Bateau", burger: "Dry-Aged Burger", price: 25.00, source: "menu", category: "premium" },
    { restaurant: "Eden Hill", burger: "Wagyu Burger", price: 23.00, source: "website", category: "premium" },
    { restaurant: "The Walrus", burger: "Smoked Brisket Burger", price: 20.00, source: "menu", category: "premium" },
  ],
  "2026-02-02": [
    { restaurant: "McDonald's", burger: "Big Mac", price: 6.49, source: "menu", category: "fast_food" },
    { restaurant: "Five Guys", burger: "Cheeseburger", price: 11.99, source: "menu", category: "fast_food" },
    { restaurant: "Shake Shack", burger: "ShackBurger", price: 8.49, source: "website", category: "fast_food" },
    { restaurant: "Dick's Drive-In", burger: "Dick's Deluxe", price: 4.50, source: "menu", category: "fast_food" },
    { restaurant: "Uneeda Burger", burger: "Classic Burger", price: 15.00, source: "menu", category: "casual" },
    { restaurant: "Red Mill Burgers", burger: "Red Mill Bacon Burger", price: 11.50, source: "website", category: "casual" },
    { restaurant: "Lil Woody's", burger: "Lil Woody's Burger", price: 12.50, source: "doordash", category: "casual" },
    { restaurant: "Katsu Burger", burger: "Original Katsu Burger", price: 14.00, source: "menu", category: "casual" },
    { restaurant: "Bateau", burger: "Dry-Aged Burger", price: 25.00, source: "menu", category: "premium" },
    { restaurant: "Eden Hill", burger: "Wagyu Burger", price: 23.00, source: "website", category: "premium" },
    { restaurant: "The Walrus", burger: "Smoked Brisket Burger", price: 20.00, source: "menu", category: "premium" },
  ],
  "2026-02-10": [
    { restaurant: "McDonald's", burger: "Big Mac", price: 6.49, source: "menu", category: "fast_food" },
    { restaurant: "Five Guys", burger: "Cheeseburger", price: 11.99, source: "menu", category: "fast_food" },
    { restaurant: "Shake Shack", burger: "ShackBurger", price: 8.79, source: "website", category: "fast_food" },
    { restaurant: "Dick's Drive-In", burger: "Dick's Deluxe", price: 4.50, source: "menu", category: "fast_food" },
    { restaurant: "Uneeda Burger", burger: "Classic Burger", price: 15.00, source: "menu", category: "casual" },
    { restaurant: "Red Mill Burgers", burger: "Red Mill Bacon Burger", price: 11.50, source: "website", category: "casual" },
    { restaurant: "Lil Woody's", burger: "Lil Woody's Burger", price: 12.50, source: "doordash", category: "casual" },
    { restaurant: "Katsu Burger", burger: "Original Katsu Burger", price: 14.50, source: "menu", category: "casual" },
    { restaurant: "Bateau", burger: "Dry-Aged Burger", price: 26.00, source: "menu", category: "premium" },
    { restaurant: "Eden Hill", burger: "Wagyu Burger", price: 23.00, source: "website", category: "premium" },
    { restaurant: "The Walrus", burger: "Smoked Brisket Burger", price: 20.00, source: "menu", category: "premium" },
  ],
};

export const BOSTON_SPOTLIGHTS: Record<string, { restaurant_name: string; burger_name: string; price: number; description: string }> = {
  "2025-12-29": { restaurant_name: "Tasty Burger", burger_name: "Tasty Burger", price: 8.95, description: "The value play of the week. While premium joints push past $24, Tasty Burger delivers a solid patty at under $9. Our analysts rate this a strong buy." },
  "2026-01-05": { restaurant_name: "Mr. Bartley's", burger_name: "Bartley's Classic", price: 14.95, description: "A Harvard Square institution seeing modest price action this week. The classic remains a benchmark for the Boston casual segment." },
  "2026-01-12": { restaurant_name: "Five Guys", burger_name: "Cheeseburger", price: 11.99, description: "Five Guys posts a 30-cent uptick this week, signaling continued fast-food inflation. Still, the customizable toppings provide value alpha." },
  "2026-01-19": { restaurant_name: "Waypoint", burger_name: "Wagyu Smash Burger", price: 23.00, description: "Premium segment on the move. Waypoint's Wagyu sees a $1 bump, but the quality-to-price ratio keeps institutional burger investors bullish." },
  "2026-01-26": { restaurant_name: "Boston Burger Co.", burger_name: "The Bostonian", price: 16.99, description: "The Bostonian crosses the $17 threshold. Our analysis suggests this reflects broader casual-segment inflation, not a supply issue." },
  "2026-02-02": { restaurant_name: "Shake Shack", burger_name: "ShackBurger", price: 8.99, description: "Shake Shack inches toward $9 as the fast-casual bellwether shows no signs of price resistance. Volume remains strong despite the uptick." },
  "2026-02-10": { restaurant_name: "JM Curley", burger_name: "Curley Burger", price: 17.00, description: "Downtown Boston's sleeper pick holds steady at $17. The Curley Burger represents stability in a market showing upward volatility across segments." },
};

export const SEATTLE_SPOTLIGHTS: Record<string, { restaurant_name: string; burger_name: string; price: number; description: string }> = {
  "2025-12-29": { restaurant_name: "Dick's Drive-In", burger_name: "Dick's Deluxe", price: 4.25, description: "The undisputed value champion. At $4.25, Dick's Deluxe is the most undervalued asset in the Seattle burger market. A defensive position in any portfolio." },
  "2026-01-05": { restaurant_name: "Red Mill Burgers", burger_name: "Red Mill Bacon Burger", price: 10.75, description: "Red Mill continues to anchor the casual segment. The Bacon Burger is a reliable mid-market holding with consistent quality metrics." },
  "2026-01-12": { restaurant_name: "Uneeda Burger", burger_name: "Classic Burger", price: 14.50, description: "Fremont's favorite sees a 50-cent appreciation. Market watchers note this reflects the neighborhood's rising culinary index." },
  "2026-01-19": { restaurant_name: "Katsu Burger", burger_name: "Original Katsu Burger", price: 14.00, description: "The fusion play. Katsu Burger's Japanese-inspired offering represents the innovation sector of Seattle's burger economy. Unique exposure." },
  "2026-01-26": { restaurant_name: "Eden Hill", burger_name: "Wagyu Burger", price: 23.00, description: "Eden Hill's premium position strengthens with a $1 increase. The Wagyu premium continues to outperform broader market trends." },
  "2026-02-02": { restaurant_name: "Lil Woody's", burger_name: "Lil Woody's Burger", price: 12.50, description: "The mid-cap darling of Capitol Hill posts another 50-cent gain. Our analysts view this as a reflection of the smash burger boom." },
  "2026-02-10": { restaurant_name: "Bateau", burger_name: "Dry-Aged Burger", price: 26.00, description: "Bateau breaks the $26 barrier, establishing new highs in the ultra-premium segment. Dry-aging premiums continue to widen versus conventional." },
};

export const MARKET_REPORTS: Record<string, { headline: string; summary: string; factors: MarketFactor[] }> = {
  "2025-12-29": {
    headline: "Year-End Burger Rally: Holiday Grilling Pushes Prices Steady",
    summary: "The Burger Price Index closed out 2025 with remarkable stability, as both Boston and Seattle showed minimal price movement heading into the new year. Analysts attribute this to the seasonal \"holiday grill plateau\" — a phenomenon where restaurants freeze prices to maintain foot traffic during the competitive year-end dining season.\n\nThe Boston BPI held firm in the mid-$14 range while Seattle maintained its slight discount advantage. Dick's Drive-In in Seattle continues to anchor the low end of the market at $4.25, a price point that hasn't moved since Q3 2025. Premium segments in both cities remain elevated but stable.",
    factors: [
      { factor: "Holiday Dining Season", impact: "neutral", description: "Restaurants hold prices steady to maintain holiday foot traffic" },
      { factor: "Beef Wholesale Prices", impact: "up", description: "USDA Choice beef futures up 1.8% month-over-month" },
      { factor: "Seasonal Labor Costs", impact: "up", description: "Holiday staffing premiums adding 3-5% to operating costs" },
    ],
  },
  "2026-01-05": {
    headline: "New Year, New Prices: Boston Premium Segment Edges Higher",
    summary: "The first week of 2026 brings subtle upward pressure to the Burger Price Index as Boston's premium segment nudges higher. Grill 23's Prime Burger ticked up $1 to $27, suggesting that fine-dining establishments are passing through year-end cost adjustments to consumers.\n\nSeattle's market remained largely unchanged, with The Walrus posting a modest 50-cent increase to $19.50. The fast-food floor in both markets held steady, indicating that chain pricing strategies remain locked in for Q1. Volume metrics suggest consumers are returning to post-holiday dining patterns.",
    factors: [
      { factor: "Q1 Menu Repricing", impact: "up", description: "Annual menu price adjustments taking effect at premium venues" },
      { factor: "Consumer Sentiment", impact: "neutral", description: "Post-holiday spending normalizing; burger demand steady" },
      { factor: "Energy Costs", impact: "down", description: "Natural gas prices down 4%, reducing kitchen operating costs" },
    ],
  },
  "2026-01-12": {
    headline: "Five Guys Hikes Signal Fast-Food Inflation Wave",
    summary: "This week's BPI data reveals a concerning trend: Five Guys Boston has bumped its Cheeseburger to $11.99, a 30-cent increase that our analysts believe signals a broader fast-food inflation wave. Shake Shack followed with similar adjustments across both markets, suggesting coordinated supply-chain cost passthrough.\n\nThe casual segment showed mixed signals. Boston's Tasty Burger and Boston Burger Co. both posted increases, while Seattle's Red Mill held firm. The premium sector remained stable, indicating that inflation pressure is currently concentrated in the fast-food and casual segments.",
    factors: [
      { factor: "Supply Chain Costs", impact: "up", description: "Fast-food chains passing through 2025 ingredient cost increases" },
      { factor: "Tomato Futures", impact: "up", description: "Winter tomato prices up 12% due to Florida cold snap" },
      { factor: "Competition", impact: "down", description: "New smash burger openings in both markets adding competitive pressure" },
    ],
  },
  "2026-01-19": {
    headline: "Boston BPI Surges Past $15 as Premium Sector Rallies",
    summary: "The Boston Burger Price Index crossed the psychologically important $15 threshold this week, driven by broad-based price increases across all three segments. McDonald's Big Mac is now $6.69 in Boston — the highest recorded level in our dataset — while Waypoint's Wagyu pushed to $23.\n\nSeattle saw comparatively modest movement, with Five Guys and McDonald's posting small increases. The inter-city spread widened to its largest gap since tracking began, raising questions about regional cost-of-living divergence in the burger sector. Dick's Drive-In remains the outlier, holding at $4.25.",
    factors: [
      { factor: "Boston Real Estate", impact: "up", description: "Commercial rent increases in Back Bay and Seaport pushing restaurant costs higher" },
      { factor: "Cattle Futures", impact: "up", description: "Live cattle futures up 2.1% on tighter supply forecasts" },
      { factor: "Seattle Min Wage", impact: "neutral", description: "Seattle's $20.76 minimum wage absorbed; no new increases until July" },
    ],
  },
  "2026-01-26": {
    headline: "Smash Burger Boom Lifts Casual Segment to New Heights",
    summary: "The smash burger trend continues to reshape the casual segment of the Burger Price Index. Boston Burger Co.'s Bostonian and Tasty Burger both posted price increases this week, while Seattle's Lil Woody's and Uneeda Burger held steady at elevated levels. The premiumization of casual burgers appears to be a structural shift rather than a temporary trend.\n\nMeanwhile, the premium segment showed continued strength with Seattle's Eden Hill and Stockyard both moving higher. Our cross-market analysis suggests that the $20-$25 price band is becoming increasingly crowded, which may trigger differentiation-driven price competition in Q2.",
    factors: [
      { factor: "Smash Burger Trend", impact: "up", description: "Premium preparation methods driving casual prices toward premium territory" },
      { factor: "Cheese Prices", impact: "up", description: "American cheese wholesale up 6% as dairy markets tighten" },
      { factor: "Weather", impact: "neutral", description: "Mild winter in both markets maintaining foot traffic at seasonal norms" },
    ],
  },
  "2026-02-02": {
    headline: "Super Bowl Week: Boston BPI Hits All-Time High on Demand Surge",
    summary: "Super Bowl anticipation is fueling a demand-driven price surge in the Boston burger market. Five Guys crossed the $12 threshold while Shake Shack pushed toward $9 — both all-time highs in our Boston dataset. The Waypoint Wagyu Smash Burger hit $24, marking a $2 increase from its December baseline.\n\nSeattle's market is also showing upward momentum but at a more measured pace. Five Guys Seattle matched its Boston counterpart at $11.99, suggesting national pricing alignment at the chain level. Our Super Bowl Impact Model estimates a 2-3% demand premium that should normalize by mid-February.",
    factors: [
      { factor: "Super Bowl Demand", impact: "up", description: "Game-day anticipation driving 15-20% volume increase at burger venues" },
      { factor: "Beef Inflation", impact: "up", description: "USDA all-fresh beef index up 3.2% year-over-year" },
      { factor: "Valentine's Proximity", impact: "neutral", description: "Some premium spots holding prices ahead of Valentine's prix fixe menus" },
    ],
  },
  "2026-02-10": {
    headline: "Post-Super Bowl Correction Fails to Materialize as BPI Holds Firm",
    summary: "Contrary to analyst expectations, the post-Super Bowl price correction has not materialized. The Boston BPI holds near its all-time high as Mr. Bartley's and Tasty Burger both posted modest increases. The JM Curley Burger remains anchored at $17, providing a stability benchmark in the volatile casual segment.\n\nSeattle continues its steady ascent with Bateau's Dry-Aged Burger breaking the $26 barrier — the highest single-item price in our entire dataset. The Shake Shack convergence continues, with the Seattle location now at $8.79, narrowing the gap with Boston's $8.99. Our Q1 outlook remains bullish for both markets.",
    factors: [
      { factor: "Sticky Prices", impact: "up", description: "Post-event prices not reverting, suggesting permanent repricing in both markets" },
      { factor: "Dry-Aging Premium", impact: "up", description: "Dry-aged beef commands 25-40% premium over conventional, widening gap" },
      { factor: "Delivery Platform Fees", impact: "neutral", description: "DoorDash and UberEats fee stabilization keeping delivery surcharges flat" },
    ],
  },
};
